### ISSUE TITLE
javax.script.ScriptException due to null java.lang.System.console() in mvn release:perform

### ISSUE THREAD

**Issue by cthiebaud** [SAP-archive/cloud-maven-plugin#2]
I am working on the update of my abendrot tutorial to the new release 1.0.1.RELEASE of nwcloud-maven-plugin.

I stumbled on the following error:
[INFO] [ERROR] Failed to execute goal com.sap.research:nwcloud-maven-plugin:1.0.1.RELEASE:stop (after.deploy) on project runciter: Failed to execute: Executing
Ant script: usage.build.xml [stop]: Failed to execute. javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: TypeError: Cannot call method "writer" of null (<Unknown source>#97) in <Unknown source> at line number 97 -> [Help 1]

Explanation:

The abendrot tutorial demonstrates how to run mvn release:prepare in batch mode (the goal is full automation), that is, with the --batch-mode maven option.

The actual execution of release:prepare is fine (nwcloud goals are not part of it).

mvn release:perform hooks nwcloud goals stop+deploy+start

when running mvn release:perform , if the password cannot be inferred from maven settings (my fault, let say I made a typo), then the error above is raised.

this is because var syscon = java.lang.System.console(); around line 343 of usage.build.xml line returns null.

**Comment by mispdev** [comment]
I included Christophe's commit c030ee2 from his pull request / issue #3 to fix the bug.
