### ISSUE TITLE
Undeploy target is broken

### ISSUE THREAD

**Issue by zbigniew-mandziejewicz** [SAP-archive/cloud-maven-plugin#4]
Attempt to execute nwcloud:undeploy target fails with following error:
[ERROR] Failed to execute goal com.sap.research:nwcloud-maven-plugin:1.0.1.RELEASE:undeploy (default-cli) on project standalone-pom: Failed to execute: Executing Ant script: usage.build.xml [undeploy]: Failed to execute. [someapp]\${sdk.dir}\tools\lib\cmd does not exist. -> [Help 1]

**Comment by mispdev** [comment]
This does not look like a bug. The error description shows that the settings variable pointing to the location of the Neo SDK folder is not set. Please make sure that the file `nwcloud.properties` exists and is located in the main project directory (where `pom.xml` is located). Then make sure to correctly define the `sdk.dir` setting in that file. It should point to the folder containing the Neo SDK. The line should look similar to this (on a Windows machine):

```
sdk.dir=c:\\Program Files\\Neo-SDK
```

Please refer to the section "Template for nwcloud.properties file" in the appendix of the `README.md` to find a complete, commented template of the `nwcloud.properties` file.
