### ISSUE TITLE
javax.script.ScriptException using java 8

### ISSUE THREAD

**Issue by cthiebaud** [SAP-archive/cloud-maven-plugin#6]
NB. with the new release 8 of java, the javascript engine bundled with java has changed from rhino to nashorn.

The following exception is thrown when running java 8. Switching back to java 7 fixes the issue.

[ERROR] Failed to execute goal com.sap.research:nwcloud-maven-plugin:1.0.1.RELEASE:stop (after.deploy) on project runciter: Failed to execute: Executing Ant script: usage.build.xml [stop]: Failed to execute. javax.script.ScriptException: ReferenceError: "importClass" is not defined in <eval> at line number 16 -> [Help 1]

**Comment by mispdev** [comment]
Issue has been fixed with new release 1.0.2.
